In [1]:
import pandas as pd
import numpy as np

In [2]:
states_abv = {"AL":"Alabama","AK":"Alaska","AZ":"Arizona","AR":"Arkansas","CA":"California","CO":"Colorado","CT":"Connecticut","DE":"Delaware","FL":"Florida","GA":"Georgia","HI":"Hawaii","ID":"Idaho","IL":"Illinois","IN":"Indiana","IA":"Iowa","KS":"Kansas","KY":"Kentucky","LA":"Louisiana","ME":"Maine","MD":"Maryland","MA":"Massachusetts","MI":"Michigan","MN":"Minnesota","MS":"Mississippi","MO":"Missouri","MT":"Montana","NE":"Nebraska","NV":"Nevada","NH":"New Hampshire","NJ":"New Jersey","NM":"New Mexico","NY":"New York","NC":"North Carolina","ND":"North Dakota","OH":"Ohio","OK":"Oklahoma","OR":"Oregon","PA":"Pennsylvania","RI":"Rhode Island","SC":"South Carolina","SD":"South Dakota","TN":"Tennessee","TX":"Texas","UT":"Utah","VT":"Vermont","VA":"Virginia","WA":"Washington","WV":"West Virginia","WI":"Wisconsin","WY":"Wyoming"}

In [5]:
df = pd.read_csv('Resources/confirmed-covid-19-cases-in-us-by-state-and-county.csv')
df2 = df.groupby(['state_name', 'date'],as_index=False)['confirmed'].agg('sum')
fullname = df2['state_name'].map(states_abv)
df2['state_name'] = fullname
df = df2
df = df.fillna('District of Columbia')

     state_name        date  confirmed
0        Alaska  2020-01-22          0
1        Alaska  2020-01-23          0
2        Alaska  2020-01-24          0
3        Alaska  2020-01-25          0
4        Alaska  2020-01-26          0
5        Alaska  2020-01-27          0
6        Alaska  2020-01-28          0
7        Alaska  2020-01-29          0
8        Alaska  2020-01-30          0
9        Alaska  2020-01-31          0
10       Alaska  2020-02-01          0
11       Alaska  2020-02-02          0
12       Alaska  2020-02-03          0
13       Alaska  2020-02-04          0
14       Alaska  2020-02-05          0
15       Alaska  2020-02-06          0
16       Alaska  2020-02-07          0
17       Alaska  2020-02-08          0
18       Alaska  2020-02-09          0
19       Alaska  2020-02-10          0
20       Alaska  2020-02-11          0
21       Alaska  2020-02-12          0
22       Alaska  2020-02-13          0
23       Alaska  2020-02-14          0
24       Alaska  2020-02-15          0
25       Alaska  2020-02-16          0
26       Alaska  2020-02-17          0
27       Alaska  2020-02-18          0
28       Alaska  2020-02-19          0
29       Alaska  2020-02-20          0
...         ...         ...        ...
4968    Wyoming  2020-03-30         95
4969    Wyoming  2020-03-31        120
4970    Wyoming  2020-04-01        137
4971    Wyoming  2020-04-02        153
4972    Wyoming  2020-04-03        166
4973    Wyoming  2020-04-04        187
4974    Wyoming  2020-04-05        199
4975    Wyoming  2020-04-06        212
4976    Wyoming  2020-04-07        221
4977    Wyoming  2020-04-08        230
4978    Wyoming  2020-04-09        239
4979    Wyoming  2020-04-10        252
4980    Wyoming  2020-04-11        261
4981    Wyoming  2020-04-12        270
4982    Wyoming  2020-04-13        275
4983    Wyoming  2020-04-14        282
4984    Wyoming  2020-04-15        288
4985    Wyoming  2020-04-16        296
4986    Wyoming  2020-04-17        305
4987    Wyoming  2020-04-18        309
4988    Wyoming  2020-04-19        313
4989    Wyoming  2020-04-20        317
4990    Wyoming  2020-04-21        322
4991    Wyoming  2020-04-22        326
4992    Wyoming  2020-04-23        332
4993    Wyoming  2020-04-24        349
4994    Wyoming  2020-04-25        361
4995    Wyoming  2020-04-26        368
4996    Wyoming  2020-04-27        389
4997    Wyoming  2020-04-28        396

[4998 rows x 3 columns]

In [6]:
df.to_csv("CSVs/confirmed_by_date.csv", index=False)